// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Moinsa.Arcante.Company.Domain.Entities;
using Moinsa.Arcante.Company.Infraestructure.Data;
using System;
using System.Collections.Generic;

namespace Moinsa.Arcante.Company.Infraestructure.Data.Configurations
{
    public partial class ApplicationsConfiguration : IEntityTypeConfiguration<Applications>
    {
        public void Configure(EntityTypeBuilder<Applications> entity)
        {
            entity.Property(e => e.Fxaltareg)
                .HasColumnType("datetime")
                .HasColumnName("fxaltareg");

            entity.Property(e => e.Fxmodreg)
                .HasColumnType("datetime")
                .HasColumnName("fxmodreg");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Applications> entity);
    }
}
